# =====================================================
# GitHub Pages Config with Architect Jekyll Theme
# =====================================================

title: "Breast Cancer Classification with EfficientNet"
description: "A deep learning project using EfficientNet and Flask to classify histopathological images of breast cancer into 8 classes."
theme: jekyll-theme-architect

# URL settings (update these with your repo details)
url: "https://Kholay47.github.io"   # your GitHub Pages URL
baseurl: "/BreakHis-Classification-and-Prediction-Model"              # the repo name if not publishing from username.github.io

# Author details
author:
  name: "Aayush Kholay"
  email: "aayushkholay@gmail.com"

# Social links
social_links:
  github: Kholay47
  linkedin: aayush-kholay
